### PR TITLE
fix: Support subpath for tsc with moduleResolutin node

### LINKED ISSUE #114: Cannot import `oas31` using ESM in `openapi3-ts@4.1.1`
While trying to upgrade to `openapi3-ts@4.1.1` in my project, I suddenly started getting this error on all my imports:

```
import { oas31 } from 'openapi3-ts';
         ^^^^^
SyntaxError: Named export 'oas31' not found. The requested module 'openapi3-ts' is a CommonJS module, which may not support all module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:

import pkg from 'openapi3-ts';
const { oas31 } = pkg;
```

I'm guessing this is happening because my project is ESM. It used to work fine with `openapi3-ts@4.0.4`.

I'm using TypeScript 5.0.4, and my `tsconfig.json` looks like this:

```json
{
  "compilerOptions": {
    "lib": ["ESNext", "dom"],
    "target": "ESNext",
    "module": "ESNext",
    "moduleResolution": "NodeNext",
    "esModuleInterop": true,
    "forceConsistentCasingInFileNames": true,
    "strict": true,
    "skipLibCheck": true,
    "experimentalDecorators": true,
    "emitDecoratorMetadata": true,
    "resolveJsonModule": true,
    "outDir": "dist"
  }
}
```

### PR DESCRIPTION
**Pull request by koooge**
resolves #114

### CODE REVIEW

**Review by pjmolina — APPROVED** [review]

**Comment by pjmolina** [comment]
Is the PR ready @koooge or should await for any missing issue before merging? Thanks for the good work, BTW.

**Comment by koooge** [comment]
@pjmolina Now it's ready to review!

**Review by pjmolina — APPROVED** [review]
looks good to me!

**Comment by RobinTail** [comment]
Thank you for fixing this

**Pull request merged**
